name: Test react-core-components

on:
  pull_request:
    branches:
      - master
    paths:
      - 'packages/components/**'

  push:
    branches:
      - master
    paths:
      - 'packages/components/**'

jobs:
  build:
    if: github.event.pull_request.draft == false
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup module dependencies cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install module dependencies
        run: yarn bootstrap:components

      - name: Lint javascript
        run: yarn workspace @untile/react-core-components lint:js

      - name: Lint styles
        run: yarn workspace @untile/react-core-components lint:styles

      - name: Lint types
        run: yarn workspace @untile/react-core-components lint:types

      - name: Jest tests
        run: yarn workspace @untile/react-core-components test

      - name: Build
        run: yarn workspace @untile/react-core-components build

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.js
